const data = {
    products: [
        {
            _id: '1',
            name: 'Arcsaber 11',
            category: 'Racket',
            image: '/images/p1.jpg',
            price: 20,
            brand: 'Yonex',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality racket',
        },
        {
            _id: '2',
            name: 'Arcsaber 10',
            category: 'Racket',
            image: '/images/p1.jpg',
            price: 10,
            brand: 'Yonex',
            rating: 4,
            numReviews: 10,
            description: 'high quality racket',
        },
        {
            _id: '3',
            name: 'Arcsaber 1',
            category: 'Racket',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Yonex',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality racket',
        },
        {
            _id: '4',
            name: 'Arcsaber 15',
            category: 'Racket',
            image: '/images/p1.jpg',
            price: 12,
            brand: 'Yonex',
            rating: 5,
            numReviews: 10,
            description: 'high quality racket',
        },
        {
            _id: '5',
            name: 'Arcsaber 19',
            category: 'Racket',
            image: '/images/p1.jpg',
            price: 0,
            brand: 'Yonex',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality racket',
        },
    ],
};
export default data;